name: CI - UI tests

on:
  push:
    paths:
      - "tests/ui/**"
      - "src/ui/**"
      - ".github/workflows/ci-ui.yml"
      - "requirements.txt"
      - "pytest.ini"
  pull_request:
    paths:
      - "tests/ui/**"
      - "src/ui/**"
      - ".github/workflows/ci-ui.yml"
      - "requirements.txt"
      - "pytest.ini"

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    env:
      HEADLESS: "true"          # run headless mode
      PYTHONDONTWRITEBYTECODE: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests de UI
        run: |
          pytest -q tests/ui

      - name: Publicar reportes (opcional si generas .html / logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-artifacts
          path: |
            .pytest_cache
            reports/**
            logs/**
          if-no-files-found: ignore
